name: My first workflow
on:
  push:
    branches: final

jobs:
  info:
    runs-on: ubuntu-22.04
    env:
      GREETING: My Special String
    steps:
      - run: echo "$GITHUB_ACTOR says $GREETING"
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ secrets.ARTIFACT_NAME }}
          path: _site
